# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-18 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='price',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
