# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-24 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20170924_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='sensitivity',
            field=models.CharField(default='no data', max_length=20),
        ),
    ]
