# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-24 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20170924_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cable',
            field=models.CharField(default='no data', max_length=40),
        ),
        migrations.AlterField(
            model_name='album',
            name='frequency',
            field=models.CharField(default='no data', max_length=20),
        ),
        migrations.AlterField(
            model_name='album',
            name='impedance',
            field=models.CharField(default='no data', max_length=20),
        ),
        migrations.AlterField(
            model_name='album',
            name='noise',
            field=models.CharField(default='no data', max_length=40),
        ),
    ]
